apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: argocd-demo-app
  template:
    metadata:
      labels:
        app: argocd-demo-app
    spec:
      containers:
        - name: argocd-demo-app
          image: ghcr.io/kaisburwais/argocd-demo-app:16c94340701470bb78e6fc51486f38272c4ca21b
          ports:
            - containerPort: 3000